spring.application.name=SwaggerDocker
# H2 Database Configuration (DEVELOPMENT/TESTING)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# JPA Configuration for H2

spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
# H2 Console

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.password=
spring.datasource.username=sa
spring.datasource.url=jdbc:h2:mem:testdb